---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data
  storageClassName: sql-storage
